tenant:
  hostname: "env527156.mycloud-eu-central-1.softwareag.cloud"   # webMthodsIO Integration hostname or ip address
  port: "443"                                       # webMthodsIO Integration port
  admin_username: "rajasekaranelango.r99@gmail.com"                     # webMthodsIO Integration user
  type: "play"   